import { useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Mic } from 'lucide-react'
import GeminiSparkle from '../components/GeminiSparkle'
import AILoadingScreen from '../AILoadingScreen.jsx'
import { useApp } from '../context/AppContext'

// Mock AI script generator — replace with a real API response.
const MOCK_STORY = (idea) => {
  const seed = idea.trim() || 'a lone traveller returning to their village in Bharat'
  return `TITLE: Echoes of Solitude

LOGLINE
A story about ${seed} — where silence becomes the loudest voice.

[SCENE 1 — DUSK / OPEN COURTYARD]
The wind carries dust across an empty courtyard. A single lamp flickers.
NARRATOR (V.O.): "Some stories are not spoken. They are felt in the quiet."

[SCENE 2 — INT. MEMORY]
Fragments of the past surface — a promise made, a road not taken.
The protagonist confronts the weight of everything left unsaid.

[CLIMAX]
In solitude, clarity arrives. The choice is made — not out of fear, but resolve.

— Generated by Pocket FM Creator Studio · adjust tone, characters & climax as needed.`
}

export default function WritePage() {
  const { focusMode, setFocusMode } = useApp()
  const [text, setText] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [storyOutput, setStoryOutput] = useState(null)

  const handleSend = () => {
    setStoryOutput(null)
    setIsLoading(true)
    // Mock latency = 2 full carton loops (CYCLE 8s x 2). Later: end when the
    // real API response arrives instead of this fixed timeout.
    setTimeout(() => {
      setIsLoading(false)
      setStoryOutput(MOCK_STORY(text))
    }, 16000)
  }

  const handleReset = () => {
    setIsLoading(false)
    setStoryOutput(null)
    setText('')
  }

  // Full-bleed loading takeover while the AI "thinks"
  if (isLoading) {
    return (
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.4 }}
        className="h-[calc(100vh-4rem)] w-full bg-black"
      >
        <AILoadingScreen />
      </motion.div>
    )
  }

  return (
    <section className="relative flex min-h-[calc(100vh-4rem)] flex-col items-center justify-center px-6 py-12">
      <div className="w-full max-w-2xl">
        <div className="mb-10 text-center">
          <h2 className="text-2xl font-bold text-white md:text-3xl">
            Express Yourself in Solitude.
          </h2>
          <h2 className="mt-2 text-2xl font-bold text-white md:text-3xl">
            अपने मन को एकांत में रखें।
          </h2>
        </div>

        {!focusMode && !storyOutput && (
          <div className="mb-6 flex justify-center">
            <button
              onClick={() => setFocusMode(true)}
              className="rounded-full border border-[#E61C38]/40 px-5 py-2 text-sm font-medium text-[#E61C38] transition-colors hover:bg-[#E61C38]/10"
            >
              Enter Focus Mode
            </button>
          </div>
        )}

        <AnimatePresence mode="wait">
          {storyOutput ? (
            /* ---- Output ---- */
            <motion.div
              key="output"
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -16 }}
              transition={{ duration: 0.5, ease: 'easeOut' }}
              className="rounded-2xl border border-[#E61C38]/50 bg-[#0d0d0d] p-6 shadow-[0_0_50px_rgba(230,28,56,0.18)]"
            >
              <div className="mb-4 flex items-center justify-between">
                <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-[#E61C38]">
                  <GeminiSparkle className="h-4 w-4" />
                  Your Generated Script
                </div>
                <button
                  onClick={handleReset}
                  className="rounded-full border border-white/15 px-4 py-1.5 text-xs font-medium text-gray-300 transition-colors hover:border-[#E61C38]/60 hover:text-[#E61C38]"
                >
                  Start Over
                </button>
              </div>
              <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-gray-300">
                {storyOutput}
              </pre>
            </motion.div>
          ) : (
            /* ---- Input ---- */
            <motion.div
              key="input"
              initial={{ opacity: 0, scale: 0.98 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.98 }}
              transition={{ duration: 0.35, ease: 'easeInOut' }}
              className="rounded-2xl border border-red-900/40 bg-[#121212] p-4 shadow-[0_0_40px_rgba(230,28,56,0.05)]"
            >
              <textarea
                value={text}
                onChange={(e) => setText(e.target.value)}
                placeholder="मेरे नए Pocket FM कहानी के लिए विचार हैं..."
                className="h-48 w-full resize-none bg-transparent text-base text-white outline-none placeholder:text-gray-600"
              />
              <div className="mt-2 flex items-center justify-between">
                <button
                  className="rounded-full p-2 text-gray-500 transition-colors hover:text-[#E61C38]"
                  title="Voice input"
                >
                  <Mic className="h-5 w-5" strokeWidth={1.5} />
                </button>

                <button
                  onClick={handleSend}
                  className="flex items-center gap-2 rounded-full bg-white px-5 py-2 text-sm font-semibold text-black transition-all hover:bg-gray-200 active:scale-[0.98]"
                >
                  <GeminiSparkle className="h-4 w-4" />
                  Send to AI
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </section>
  )
}
