import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { AnimatePresence, motion } from 'framer-motion'
import { Languages } from 'lucide-react'
import GeminiSparkle from '../components/GeminiSparkle'
import AILoadingScreen from '../AILoadingScreen.jsx'
import StoryQuestionsModal from '../components/StoryQuestionsModal'
import { ROUTES } from '../constants/routes'

// Fullscreen API helpers
const requestFullscreen = () => {
  const el = document.documentElement
  const fn = el.requestFullscreen || el.webkitRequestFullscreen
  if (fn) Promise.resolve(fn.call(el)).catch(() => {})
}
const exitFullscreen = () => {
  if (!document.fullscreenElement && !document.webkitFullscreenElement) return
  const fn = document.exitFullscreen || document.webkitExitFullscreen
  if (fn) Promise.resolve(fn.call(document)).catch(() => {})
}

// Mock AI script generator — replace with a real API response.
const MOCK_STORY = (idea) => {
  const seed = idea.trim() || 'a lone traveller returning to their village in Bharat'
  return `TITLE: Echoes of Solitude

LOGLINE
A story about ${seed} — where silence becomes the loudest voice.

[SCENE 1 — DUSK / OPEN COURTYARD]
The wind carries dust across an empty courtyard. A single lamp flickers.
NARRATOR (V.O.): "Some stories are not spoken. They are felt in the quiet."

[SCENE 2 — INT. MEMORY]
Fragments of the past surface — a promise made, a road not taken.
The protagonist confronts the weight of everything left unsaid.

[CLIMAX]
In solitude, clarity arrives. The choice is made — not out of fear, but resolve.

— Generated by Pocket FM Creator Studio · adjust tone, characters & climax as needed.`
}

const PLACEHOLDERS = {
  en: 'Express Yourself in Solitude...',
  hi: 'अपने मन को एकांत में रखें...',
}

export default function WritePage() {
  const navigate = useNavigate()
  const [lang, setLang] = useState('en')
  const [inputText, setInputText] = useState('')
  const [showQuestions, setShowQuestions] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [storyOutput, setStoryOutput] = useState(null)
  const [isFullscreen, setIsFullscreen] = useState(false)

  // Enter fullscreen on mount
  useEffect(() => {
    requestFullscreen()
    return () => exitFullscreen()
  }, [])

  // Sync fullscreen state with browser
  useEffect(() => {
    const onChange = () =>
      setIsFullscreen(
        Boolean(document.fullscreenElement || document.webkitFullscreenElement)
      )
    document.addEventListener('fullscreenchange', onChange)
    document.addEventListener('webkitfullscreenchange', onChange)
    return () => {
      document.removeEventListener('fullscreenchange', onChange)
      document.removeEventListener('webkitfullscreenchange', onChange)
    }
  }, [])

  // Step 1: "Send to AI" opens the question modal
  const handleSend = () => {
    setShowQuestions(true)
  }

  // Step 2: all questions answered/skipped → start loading → navigate to ideaboard
  const handleQuestionsComplete = () => {
    setShowQuestions(false)
    setIsLoading(true)
    setTimeout(() => {
      setIsLoading(false)
      navigate(ROUTES.ideaboard(1))
    }, 16000)
  }

  const handleReset = () => {
    setIsLoading(false)
    setStoryOutput(null)
    setInputText('')
  }

  return (
    <div
      className="relative flex h-[calc(100vh-4rem)] w-full flex-col"
      style={{
        background: 'radial-gradient(ellipse 80% 60% at 50% 100%, rgba(100,0,15,0.18), #0a0a0a 70%)',
      }}
    >
      <AnimatePresence mode="wait">
        {isLoading ? (
          /* ---- Loading ---- */
          <motion.div
            key="loading"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.4 }}
            className="flex h-full w-full items-center justify-center"
          >
            <AILoadingScreen />
          </motion.div>

        ) : storyOutput ? (
          /* ---- Output ---- */
          <motion.div
            key="output"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            transition={{ duration: 0.5, ease: 'easeOut' }}
            className="flex flex-1 flex-col overflow-auto p-10 md:p-20"
          >
            <div className="mb-6 flex items-center justify-between">
              <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-[#E61C38]">
                <GeminiSparkle className="h-4 w-4" />
                Your Generated Script
              </div>
              <button
                onClick={handleReset}
                className="rounded-full border border-white/15 px-4 py-1.5 text-xs font-medium text-gray-300 transition-colors hover:border-[#E61C38]/60 hover:text-[#E61C38]"
              >
                Start Over
              </button>
            </div>
            <pre
              className="flex-1 whitespace-pre-wrap text-base leading-8 text-gray-200"
              style={{ fontFamily: "'JetBrains Mono', monospace", fontWeight: 300 }}
            >
              {storyOutput}
            </pre>
          </motion.div>

        ) : (
          /* ---- Input (iA Writer style) ---- */
          <motion.div
            key="input"
            initial={{ opacity: 0, scale: 0.99 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.99 }}
            transition={{ duration: 0.35, ease: 'easeInOut' }}
            className="flex flex-1 flex-col"
          >
            {/* Giant dark writing box */}
            <div
              className="relative mx-auto my-8 flex flex-1 w-full max-w-5xl flex-col rounded-2xl"
              style={{
                border: '1.5px solid rgba(180,20,40,0.25)',
                boxShadow: '0 0 60px rgba(180,20,40,0.12), inset 0 0 40px rgba(0,0,0,0.4)',
                background: '#0e0e0e',
              }}
            >
              <textarea
                autoFocus
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                placeholder={PLACEHOLDERS[lang]}
                className="flex-1 w-full resize-none bg-transparent px-10 pt-10 pb-4 text-white text-xl md:text-2xl leading-9 tracking-wide outline-none placeholder:text-white/40"
                style={{
                  minHeight: 'calc(100vh - 240px)',
                  fontFamily: "'JetBrains Mono', monospace",
                  fontWeight: 300,
                }}
              />

              {/* Bottom bar */}
              <div className="flex items-center justify-between border-t border-white/5 px-8 py-4">
                <button
                  onClick={() => setLang(l => l === 'en' ? 'hi' : 'en')}
                  className="flex items-center gap-1.5 text-sm text-white/25 transition-colors hover:text-white/70"
                >
                  <Languages size={15} strokeWidth={1.5} />
                  <span className="font-medium">{lang === 'en' ? 'EN' : 'हिं'}</span>
                </button>

                <button
                  onClick={handleSend}
                  disabled={!inputText.trim()}
                  className="flex items-center gap-2.5 rounded-full bg-[#E61C38] px-6 py-2.5 text-sm font-semibold text-white transition-all shadow-[0_0_24px_rgba(230,28,56,0.35)] hover:bg-[#ff2244] disabled:opacity-25 disabled:shadow-none active:scale-95"
                >
                  <GeminiSparkle className="h-3.5 w-3.5" />
                  Send to AI
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Question modal — overlays the write view, animates in/out */}
      <AnimatePresence>
        {showQuestions && (
          <StoryQuestionsModal
            onComplete={handleQuestionsComplete}
            onClose={() => setShowQuestions(false)}
          />
        )}
      </AnimatePresence>
    </div>
  )
}
